functional:
 - создание пробной игры без регистрации
 - классическая регистрация нового пользователя
 - регистрация нового пользователя с помощью сторонних сайтов и ресурсов
 - авторизация зарегистрированного пользователя
 - восстановление забытого пароля
 - создание игр, выбор режимов игр, выбор сложности игр
 - поддержка не менее 10 самых восстребованных языков программирования
 - создание турниров
 - наличие пользовательского чата
 - просмотр и различная сортировка таблицы рейтингов пользователей
non-functional:
 - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - сайт должен быть безопасным и защищать данные пользователя
 - сайт должен быть удобным на мобильном устройстве
 - сайт должен быть протестирован на совместимость с последними версиями браузеров
 - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
 - пользователь должен иметь возможность отправки приглашения на турнир
