functional:
 - пользователь должен иметь возможность создания пробной игры без регистрации
 - пользователь должен иметь возможность регистрации через email
 - пользователь должен иметь возможность регистрации и авторизации через Discord и Github
 - пользователь должен иметь возможность восстановить забытый пароль
 - пользователь должен иметь возможность создавать игру с ботом и с другим пользователем
 - пользователь должен иметь возможность вибирать сложность игры
 - пользователь должен иметь возможность выбрать для решения задачи один из 12 языков программирования (JavaScript, Java, Python, C#, С++, Ruby, Go, Rust, PHP, TypeScript, Kotlin, Elixir)
 - пользователь должен иметь возможность создания турниров между пользователями
 - пользователи должны иметь возможность общаться в чате игры
 - пользователи должны иметь возможность просмотра и сортировки таблицы рейтингов пользователей
non-functional:
 - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - сайт должен быть безопасным и защищать данные пользователя
 - сайт должен быть удобным на мобильном устройстве
 - сайт должен быть протестирован на совместимость с последними версиями браузеров (Chrome, Safari, Edge, Firefox, Opera)
 - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
 - пользователь должен иметь возможность отправки приглашения на турнир
 - пользователь видит анимацию (графику) при победе, проигрыше
 - пользователь слышит джинглы (звуковые эффекты) при победе, проигрыше
 - пользователь должен иметь личный кабинет на сайте
 - пользователь должен иметь возможность выбора цветовых, звуковых тем в личном кабинете
 - пользователь должен иметь возможность менять никнейм
 - nickname должен содержать латинские буквы, цифры и символы подчеркивания.
 - nickname пользователя не может начинаться с цифры
 - nickname пользователя должен быть от 3 до 16 символов
 - email пользователя должен содержать @
