functional:
 - создание пробной игры без регистрации
 - Классическая регистрация нового пользователя
 - регистрация нового пользователя с помощью сторонних сайтов и ресурсов
 - авторизация зарегистрированного пользователя
 - создание игр, выбор режимов игр, выбор сложности игр
 - создание турниров
non-functional:
 - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - сайт должен быть безопасным и защищать данные пользователя
 - сайт должен быть удобным на мобильном устройстве
 - сайт должен быть протестирован на совместимость с последними версиями браузеров
 - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
